name: SASjs Core Package Publish Tag
on:
  push:
    branches:
      - main
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Make Release
        uses: alice-biometrics/release-creator/@v1.0.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          draft: false
          version: 4.52.3
          description: 'Version 4.52.3 of sasjs/core is now on SAS PACKAGES :ok_hand:'
